export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE';
export const AUTH_USERS = 'AUTH_USERS';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
export const SET_AUTH_ERROR_FALSE = 'SET_AUTH_ERROR_FALSE';
export const SET_SIGNUP_STATUS = 'SET_SIGNUP_STATUS';

export const TRANS_FETCH_START = 'TRANS_FETCH_START'; 
export const TRANS_FETCH_FAIL = 'TRANS_FETCH_FAIL';
export const TRANS_READ_ALLTRANSACTION = 'TRANS_READ_ALLTRANSACTION';
export const TRANS_READ_ALLTRANSACTION_SUCCESS = 'TRANS_READ_ALLTRANSACTION_SUCCESS';

export const TRANS_ADD = 'TRANS_ADD';
export const TRANS_SUCCESS = 'TRANS_SUCCESS';
export const TRANS_DEFAULT = 'TRANS_DEFAULT';
export const TRANS_FAIL = 'TRANS_FAIL';
export const TRANS_GET_BY_ID = 'TRANS_GET_BY_ID';
export const TRANS_GET_BY_ID_SUCCESS = 'TRANS_GET_BY_ID_SUCCESS';
export const TRANS_EDIT = 'TRANS_EDIT';
export const TRANS_EDIT_TO_NULL = 'TRANS_EDIT_TO_NULL';
export const TRANS_DELETE_BY_ID = 'TRANS_DELETE_BY_ID';